Roy
rickvanderheijden/TravelAgency pull request #85
Opened 2019-06-05 18:54 UTC by RoyTimmers

2019-06-05 19:59 UTC, RoyTimmers commented
Codacy gaat fout op een package naam, maar deze package naam is altijd al zo geweest, aanpassen of niet?

Test gaat fout wanneer hij users ophaalt zonder geautoriseerd te zijn met admin wachtwoord. Deze test is niet meer van toepassing, want ik moet ook alle users ophalen als ik gebruikers wil zoeken bij het toevoegen aan een groep.

2019-06-06 06:32 UTC, rickvanderheijden requested changes

2019-06-06 06:32 UTC, rickvanderheijden commented on .idea/misc.xml
> -  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="false" project-jdk-name="12.0.1" project-jdk-type="JavaSDK">
Please undo

2019-06-06 06:32 UTC, rickvanderheijden commented on src/main/java/com/travelagency/controllers/UserController.java
> +    public UserController(AuthorityRepository authorityRepository, UserRepository userRepository, JwtTokenUtil jwtTokenUtil, TravelGroupRepository travelGroupRepository) {
Would be nicer to have the repositories together... both in the parameter list as in the assignment

2019-06-06 06:32 UTC, rickvanderheijden commented on src/main/java/com/travelagency/repository/TravelGroupRepository.java
> +    List<TravelGroup> findByUsers(User user);
rename to findByUser. You are only using one :-)

2019-06-06 20:49 UTC, RoyTimmers commented on src/main/java/com/travelagency/repository/TravelGroupRepository.java
> +    List<TravelGroup> findByUsers(User user);
Hernoemd

2019-06-07 16:21 UTC, rickvanderheijden approved these changes

2019-06-07 16:21 UTC, merged